### ISSUE TITLE
What paramters and flag values were used to achieve the results from the paper?

### ISSUE THREAD

**Issue by danielduckworth** [siyuanzhao/automated-essay-grading#1]
The paper 'A Memory-Augmented Neural Model for Automated Grading' demonstrates some very impressive accuracy scores.

https://siyuanzhao.github.io/pdf/L_S_2017.pdf

I'm trying to reproduce those results.

What parameter and flag values do I need to set to reproduce the research findings?

**Comment by siyuanzhao** [comment]
I believe most of default flag values in cv_train.py will give you the results in the paper, except that is_regression should be set to False for eassy set 1 - 7 and to True for essay set 8.

Let me know if you cannot reproduce some of the resullts.

**Comment by danielduckworth** [comment]
Thanks, I managed to reproduce the results with the original data very well. I was also able to use an entirely separate dataset (with only a total of 900 or so responses) and achieved similar results around 0.89.

I'm very impressed and excited with this model!

**Comment by eramfatima** [comment]
hey can you please share the other data set that you have used to train this model.
