### ISSUE TITLE
Multiple score features

### ISSUE THREAD

**Issue by danielduckworth** [siyuanzhao/automated-essay-grading#2]
Could this be adapted to use multiple score features instead of a single score?

**Comment by siyuanzhao** [comment]
You can use multiple scores during the training to get a weighted score label.
For instance, two give an essay 4 and one give it 3 and then score label is 2/3 for 4 and 1/3 for 3.

But I didn't try it to train the model and don't know if it helps.

**Comment by danielduckworth** [comment]
Thanks. What I mean is similar to multi label classification. So in this case it would be multiple score points per response for a variety of criteria. For example, 1-5 for expression and 1-8 for quality of ideas.
