### ISSUE TITLE
UnicodeDecode Error

### ISSUE THREAD

**Issue by poojamittal234** [siyuanzhao/automated-essay-grading#3]
Hi,

Got below error while reading the training data:
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 80: invalid start byte**

Tried all the ways, but could not read the file,
Finally converted the file from tsv to txt , and could read it( but I feel this is a workaround rather than a solution)

Got similar error while reading the glove file.
**UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2438: character maps to <undefined>**

Please provide help on this.

Regards,
Pooja

**Comment by siyuanzhao** [comment]
I believe I run into this error at some point, but I forgot how I fixed it.

**Comment by siyuanzhao** [comment]
I run into the same issue after 2 year and solved it with the help from this link.
https://stackoverflow.com/a/18172249

In summary, use pd.read_csv('file', encoding = "ISO-8859-1")
